### ISSUE TITLE
 System.Net.Sockets.SocketException (0x80004005)

### ISSUE THREAD

**Issue by yinluobing** [shadowsocksr/shadowsocksr-csharp#137]
[2017-04-14 14:14:25] [Error] System.Net.Sockets.SocketException (0x80004005): An invalid argument was supplied
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Shadowsocks.Controller.Listener.Start(Configuration config, Int32 port)
   at Shadowsocks.Controller.ShadowsocksController.Reload()
[2017-04-14 14:14:36] [Error] connect to update server error

**Comment by breakwa11** [comment]
你只发这个我还是不知道你到底遇到什么问题

**Comment by Portan** [comment]
@yinluobing 是不是检测更新失败了？我点击检测更新是没有反应，一般不应该有提示吗，比如”已经是最新版“，或是”软件有更新“之类的。
