### ISSUE TITLE
在使用csharp的时候onedrive和pixiv的访问似乎存在一些问题

### ISSUE THREAD

**Issue by antidemosthenes** [shadowsocksr/shadowsocksr-csharp#226]
1. 我希望能加速一些没被禁的国外网站的访问速度，因此pac选择的whitelist，bypass disabled。但whitelist会漏掉一些大陆域名，在log里面可以看到ssr进行了这些网站的代理，所以bypass大陆ip后问题解决了。但新的问题出现了，比如onedrive这样访问不了，disable bypass后可以访问，因而似乎onedrive有些链接用的大陆ip？
2. 关于pixiv域名。在whitelist, bypass diabled的情况下，pixiv不在whitelist里面，因此访问它会经过ssr，但不知道什么原因连接不上。我的vps是vultr日本, 客户端是ssr最新版本，log显示一会connect一会disconnect。我怀疑应该是vps自身的问题，所以尝试改whitelist的pac想把pixiv加入白名单，但修改无效。
3. 使用gfwlist并且disable bypass可以解决前面的问题，但其它没被禁的网站得手动加入user rule，操作有些繁琐，是否有其它解决办法？

**Comment by breakwa11** [comment]
@antidemosthenes 请使用代理规则代替PAC，而且你没说是什么版本

**Comment by antidemosthenes** [comment]
使用代理规则不用pac的情况下无法访问onedrive，客户端版本是4.5.0

**Comment by antidemosthenes** [comment]
dns用的是dnscrypt，没有污染

**Comment by antidemosthenes** [comment]
Global Mode开启bypass后，好像74.117.182.158被绕过导致onedrive无法访问

`[Error]System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 74.117.182.158:443

at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
at Shadowsocks.Controller.Socks5Forwarder.Handler.ConnectCallback(IAsyncResult ar)`

**Comment by antidemosthenes** [comment]
在host.txt中添加pixiv为localproxy后解决了问题，但添加.live.com remoteproxy或者onedrive.live.com remoteproxy并重启过客户端后还是连不上onedrive，查了下ip也不在chn_ip.txt里面，请问怎么获知在登陆onedrive.live.com时哪些域名或者ip没有被代理？

**Comment by breakwa11** [comment]
@antidemosthenes 查LOG，LOG里面有记录连接的方式

**Comment by antidemosthenes** [comment]
[2017-06-15 23:38:03] [Info] Connect 195.122.177.189:443
[2017-06-15 23:38:04] [Info] Connect 195.122.177.189:443
[2017-06-15 23:38:04] [Info] Connect d3cbihxaqsuq0s.cloudfront.net:443
[2017-06-15 23:38:17] [Info] Connect 195.122.177.189:443
[2017-06-15 23:38:19] [Error] System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 31.13.84.36:443
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Socks5Forwarder.Handler.ConnectCallback(IAsyncResult ar)
[2017-06-15 23:38:38] [Error] System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 31.13.84.36:443
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Socks5Forwarder.Handler.ConnectCallback(IAsyncResult ar)
[2017-06-15 23:38:39] [Info] Disconnect 195.122.177.189:443
[2017-06-15 23:38:39] [Info] Disconnect 195.122.177.189:443
[2017-06-15 23:38:39] [Info] Disconnect 195.122.177.189:443
[2017-06-15 23:38:40] [Error] System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 31.13.84.36:443
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Controller.Socks5Forwarder.Handler.ConnectCallback(IAsyncResult ar)
[2017-06-15 23:38:44] [Info] Connect www.msftconnecttest.com:80
[2017-06-15 23:38:45] [Info] Connect www.msftconnecttest.com:80
[2017-06-15 23:38:45] [Info] Disconnect www.msftconnecttest.com:80
[2017-06-15 23:38:45] [Info] Connect www.msftconnecttest.com:80
[2017-06-15 23:38:45] [Info] Disconnect www.msftconnecttest.com:80
[2017-06-15 23:38:46] [Info] Connect www.msftconnecttest.com:80
[2017-06-15 23:38:46] [Info] Disconnect www.msftconnecttest.com:80

**Comment by breakwa11** [comment]
好吧，不通过服务器连接的LOG写成了debug，不出现在LOG里，你用浏览器的F12功能查一下连接的域名加入到host.txt里吧

**Comment by antidemosthenes** [comment]
debug显示onedrive EMPTY_RESPONSE。。。感觉这个问题与其说是ssr-csharp的问题不如说是微软或墙的问题。过两天还解决不了我就自动close算了。PS. android客户端下用chrome可以上。。

**Comment by antidemosthenes** [comment]
本来也是个小事情，不起用代理规则就行，只是很好奇其中机制为何不起作用。
总结一下，供其他有类似问题的人搜索，结论仅供参考：

1. 本地环境：win10创意者x64，.Net FW 4.0，chrome/IE/Edge最新(https everywhere)，dnscrypt(cs-fi, udp自定端口, ephemeral key on)，SSR-csharp 4.5.0（全局，dns指向dnscrypt）
！！服务器应该关系不大，因为不开系统代理规则可以访问，开规则不能访问
2. 服务器：vultr日本，debian 7x64，rc4-md5-6，auth_sha1_v4，tls1.2_ticket_auth，只有锐速没有kcptun之类的影响obfusca的加速
3. 依据：
    1）将连接onedrive web相关的所有域名加入host.txt后无效，出现System.Net.Sockets.SocketException (0x80004005)错误，连接的ip也没有在chn_ip.txt中。
    2）有很少的时候能连上，但文件加载不出来
    3）ie内核和webkit均不能连上
    4）中国移动，手机端Android ssr，采用绕过局域网和大陆能访问（手机的规则和csharp规则不同？）
    5）onedrive网页akamai的脚本本身有点问题
4.结论：大概率微软的锅，似乎微软会要求本地onedrive的数据，当然微软这德行要弄好也得几个月。小概率ssr-csharp代理规则有问题，或者某些连接被代理拒绝。（没有测试其它csharp版本，4.5.0host.txt的可靠性没有测试）
5.建议：可以试试python；onedrive 客户端本身在sockscap64下也没问题。
