### ISSUE TITLE
ssline.cc服务链接失效

### ISSUE THREAD

**Issue by cotes2020** [shadowsocksr/shadowsocksr-csharp#254]
客户端版本：4.1.0
运行环境：Windows10 64bit

客户端Log:
```c
[2017-07-03 23:36:22] [Debug] System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
[2017-07-03 23:36:22] [Debug] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at System.Net.DownloadStringCompletedEventArgs.get_Result()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2017-07-03 23:36:22] [Error] connect to update server error
[2017-07-03 23:36:37] [Debug] Connect github.com:443 1700
```

**另外，sscline.cc域名都打不开了，是不是服务崩溃了？？这情况都持续有两天以上了**

**Comment by breakwa11** [comment]
那个站不能访问和我有什么关系吗
